/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cilent.GUI;

import com.server.code.user;
import javax.swing.JOptionPane;
import com.server.rmiserver.*;
import java.awt.event.KeyEvent;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.SwingUtilities;

/**
 *Main menu for the game. Player can login or create new account
 * Icons in GUIs used from https://undraw.co/illustrations
 * @author Eranda
 */
public class Main_menu extends javax.swing.JFrame {

    
    com.server.code.user User;
    Registry reg = null;
    
   
    public Main_menu() {
        initComponents();
        //create user object
        User = new user();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnCreateAccount = new javax.swing.JButton();
        txtAge = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtConPassword = new javax.swing.JPasswordField();
        txtNewPassword = new javax.swing.JPasswordField();
        btnHelp = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblPasswordError = new javax.swing.JLabel();
        lblNameError = new javax.swing.JLabel();
        lblAgeError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Brain Trickles");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 137, 31));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 48, 860, 10));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 114, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Age");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 178, -1, -1));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 109, 362, 31));

        btnCreateAccount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCreateAccount.setText("Create Account");
        btnCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccountActionPerformed(evt);
            }
        });
        jPanel1.add(btnCreateAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 375, 362, 39));

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        txtAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAgeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAgeKeyReleased(evt);
            }
        });
        jPanel1.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 173, 362, 31));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Confirm Password");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 303, -1, -1));

        txtConPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtConPasswordKeyPressed(evt);
            }
        });
        jPanel1.add(txtConPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 298, 362, 31));

        txtNewPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNewPasswordKeyPressed(evt);
            }
        });
        jPanel1.add(txtNewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 235, 362, 31));

        btnHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/light-bulb_1.png"))); // NOI18N
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });
        jPanel1.add(btnHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 36, -1));

        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLogin.setText("User LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 445, 362, 41));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/undraw_Playful_cat_re_bxiu.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 490, 270, 120));

        lblPasswordError.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblPasswordError, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 360, 20));

        lblNameError.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblNameError, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 144, 360, 20));

        lblAgeError.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblAgeError, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 360, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 861, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccountActionPerformed
        // TODO add your handling code here:
       /**
        * When the create account button pressed, game will check for input errors,mismatch passwords and show alert to the player.
        * If the details are correct new account will create.
        */
        String Name;
        String Age;
        String Password;
        String ConPassword = txtConPassword.getText().trim();
        
        //setting user details from input to the user object
        User.setName(txtName.getText().trim());
        User.setAge(txtAge.getText().trim());
        User.setPassword(txtNewPassword.getText().trim());

        //getting details from the user object
        Name = User.getName();
        Age = User.getAge();
        Password = User.getPassword();
        
        //check for empty fields to prompt error message to fill 
        if(txtName.getText().equals("") || txtAge.getText().equals("")){
        
            JOptionPane.showMessageDialog(rootPane, "Please Fill the Remainning Fields! ");
        }
        
        //check weather the password and confirm password matchs
        if(!Password.equals(ConPassword) || txtNewPassword.getText().equals("") || txtConPassword.getText().equals("")){
        
            JOptionPane.showMessageDialog(rootPane, "Password didn't match! Please Try Again!");
            txtNewPassword.setText("");
            txtConPassword.setText("");
        }
        
        //check for invalid name inputs
        if(!(Pattern.matches("^[a-zA-Z\\s]{0,20}$", Name))){
        
            JOptionPane.showMessageDialog(rootPane, "Invalid Name! ");
            txtName.setText("");
        }
        
        //check for invalid age inputs
        if(!(Pattern.matches("^[0-9]{2}$", Age))){
        
            JOptionPane.showMessageDialog(rootPane, "Invalid Age! ");
            txtAge.setText("");
        }
        
        //create user account if all the fields are valid
        if(Password.equals(ConPassword) && Pattern.matches("^[a-zA-Z\\s]{0,20}$", Name) && Pattern.matches("^[0-9]{2}$", Age) && !Name.equals("") && !Age.equals("")){
        
            try {
                reg = LocateRegistry.getRegistry("localhost", 2000);
                ServiceInterface inter = (ServiceInterface) reg.lookup("RMIserver");

                //pass data to the addNewUser method in the ServiceInterface via RMI server
                inter.addNewUser(Name, Age, Password);
                
                txtName.setText("");
                txtAge.setText("");
                txtNewPassword.setText("");
                txtConPassword.setText("");
                
                System.out.println("User Added!");
                JOptionPane.showMessageDialog(rootPane, "User Added. Proceed to Login!!!");
                
                //dispose the current GUI and load the Login GUI
                this.setVisible(false);
                new Login().setVisible(true);
                
            } catch (NotBoundException | RemoteException ex) {
                System.out.println("Exception " + ex);
            }
        }

    }//GEN-LAST:event_btnCreateAccountActionPerformed
  
    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Help().setVisible(true);
    }//GEN-LAST:event_btnHelpActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        
        /**
         * If the player already have an account they can login from pressing Login button.
         */
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyPressed
        // TODO add your handling code here:
        
        /**
         * switch to the Age text field by pressing Enter button on the Keyboard
         */
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtAge.requestFocus();
        }
    }//GEN-LAST:event_txtNameKeyPressed

    private void txtAgeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyPressed
        // TODO add your handling code here:
        
        /**
         * switch to the Password text field by pressing Enter button on the Keyboard
         */
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtNewPassword.requestFocus();
        }
    }//GEN-LAST:event_txtAgeKeyPressed

    private void txtNewPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewPasswordKeyPressed
        // TODO add your handling code here:
        
        /**
         * switch to the Confirm Password text field by pressing Enter button on the Keyboard
         */
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtConPassword.requestFocus();
        }
    }//GEN-LAST:event_txtNewPasswordKeyPressed

    private void txtAgeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyReleased
        // TODO add your handling code here:
        
        /**
         * check for the age input and show an error text for invalid age input
         */
        String namePattern = "^[0-9]{0,2}$";
        Pattern patt = Pattern.compile(namePattern);
        Matcher match = patt.matcher(txtAge.getText());
        if (!match.matches()) {
            lblAgeError.setText("Incorrect Age...");
        } else {
            lblAgeError.setText(null);
        }
    }//GEN-LAST:event_txtAgeKeyReleased

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        // TODO add your handling code here:

        /**
         * check for the name input and show an error text for invalid name input
         * https://stackoverflow.com/questions/7362567/java-regex-for-full-name
         */
        String namePattern = "^[a-zA-Z\\s]{0,20}$";
        Pattern patt = Pattern.compile(namePattern);
        Matcher match = patt.matcher(txtName.getText());
        if (!match.matches()) {
            lblNameError.setText("Incorrect Name...");
        } else {
            lblNameError.setText(null);
        }
    }//GEN-LAST:event_txtNameKeyReleased

    private void txtConPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConPasswordKeyPressed
        // TODO add your handling code here:

        /**
         * switch from confirm password to Create account button from pressing Enter Key
         */
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            SwingUtilities.getRootPane(btnCreateAccount).setDefaultButton(btnCreateAccount);
        }
    }//GEN-LAST:event_txtConPasswordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateAccount;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAgeError;
    private javax.swing.JLabel lblNameError;
    private javax.swing.JLabel lblPasswordError;
    private javax.swing.JTextField txtAge;
    private javax.swing.JPasswordField txtConPassword;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtNewPassword;
    // End of variables declaration//GEN-END:variables
}
